name: Version validation

on:
  pull_request:
    branches:
      - development
      - develop
      - main
      - master
      - release-v[0-9]+.[0-9]+.[xX]

jobs:
  call-reusable-workflow:
    name: Version validation
    uses: santander-group-shared-assets/gln-workflows/.github/workflows/version-release-validation.yml@v1
    with:
      version_file: 'pom.xml'
    secrets: inherit
