CREATE TABLE JOB_DETAILS (
  ID VARCHAR2(50) NOT NULL,
  CORRELATION_ID VARCHAR2(50),
  STATUS VARCHAR2(40),
  LAST_UPDATE TIMESTAMP(6) WITH TIME ZONE,
  RETRIES NUMBER,
  EXECUTION_COUNTER NUMBER,
  SCHEDULED_ID VARCHAR2(40),
  PRIORITY NUMBER,
  RECIPIENT CLOB,
  JOB_TRIGGER CLOB,
  FIRE_TIME TIMESTAMP(6) WITH TIME ZONE,
  EXECUTION_TIMEOUT NUMBER(19,0),
  EXECUTION_TIMEOUT_UNIT VARCHAR2(40),
  CREATED TIMESTAMP(6) WITH TIME ZONE
  ,CONSTRAINT JOB_DETAILS_PKEY1 PRIMARY KEY (ID)
);

CREATE TABLE JOB_SERVICE_MANAGEMENT (
  ID VARCHAR2(40) NOT NULL,
  LAST_HEARTBEAT TIMESTAMP(6) WITH TIME ZONE,
  TOKEN VARCHAR2(40)
  ,CONSTRAINT JOB_SERVICE_MANAGEMENT_PKEY PRIMARY KEY (ID)
  ,CONSTRAINT JOB_SERVICE_MANAGEMENT_TOKEN_KEY UNIQUE (TOKEN)
);

CREATE INDEX JOB_DETAILS_CREATED_IDX ON JOB_DETAILS (SYS_EXTRACT_UTC("CREATED"));

CREATE INDEX JOB_DETAILS_FIRE_TIME_IDX ON JOB_DETAILS (SYS_EXTRACT_UTC("FIRE_TIME"));


