CREATE TABLE BUSINESS_KEY_MAPPING (
  BUSINESS_KEY VARCHAR2(255) NOT NULL,
  PROCESS_INSTANCE_ID VARCHAR2(36) NOT NULL
  ,CONSTRAINT BUSINESS_KEY_MAPPING_PKEY PRIMARY KEY (BUSINESS_KEY)
);

CREATE TABLE CORRELATION_INSTANCES (
  ID VARCHAR2(36) NOT NULL,
  ENCODED_CORRELATION_ID VARCHAR2(36) NOT NULL,
  CORRELATED_ID VARCHAR2(36) NOT NULL,
  CORRELATION VARCHAR2(255) NOT NULL,
  VERSION NUMBER(19,0)
  ,CONSTRAINT CORRELATION_INSTANCES_PKEY PRIMARY KEY (ID)
  ,CONSTRAINT CORRELATION_INSTANCES_ENCODED_CORRELATION_ID_KEY UNIQUE (ENCODED_CORRELATION_ID)
);

CREATE TABLE EVENT_TYPES (
  PROCESS_INSTANCE_ID VARCHAR2(36) NOT NULL,
  EVENT_TYPE VARCHAR2(256) NOT NULL
  ,CONSTRAINT EVENT_TYPES_PK PRIMARY KEY (PROCESS_INSTANCE_ID, EVENT_TYPE)
);

CREATE TABLE PROCESS_INSTANCES (
  ID VARCHAR2(36) NOT NULL,
  PAYLOAD BLOB NOT NULL,
  PROCESS_ID VARCHAR2(255) NOT NULL,
  VERSION NUMBER(19,0),
  PROCESS_VERSION VARCHAR2(255)
  ,CONSTRAINT PROCESS_INSTANCES_PKEY PRIMARY KEY (ID)
);

ALTER TABLE BUSINESS_KEY_MAPPING ADD CONSTRAINT FK_PROCESS_INSTANCES FOREIGN KEY (PROCESS_INSTANCE_ID) REFERENCES PROCESS_INSTANCES (ID) ON DELETE CASCADE;

CREATE INDEX IDX_BUSINESS_KEY_PROCESS_INSTANCE_ID ON BUSINESS_KEY_MAPPING (PROCESS_INSTANCE_ID);

CREATE INDEX IDX_CORRELATION_INSTANCES_CORRELATED_ID ON CORRELATION_INSTANCES (CORRELATED_ID);

CREATE INDEX IDX_PROCESS_INSTANCES_PROCESS_ID ON PROCESS_INSTANCES (PROCESS_ID, ID, PROCESS_VERSION);


