CREATE TABLE JBPM_USER_TASKS (
  ID VARCHAR2(50) NOT NULL,
  USER_TASK_ID VARCHAR2(255),
  TASK_PRIORITY VARCHAR2(50),
  ACTUAL_OWNER VARCHAR2(255),
  TASK_DESCRIPTION VARCHAR2(255),
  STATUS VARCHAR2(255),
  TERMINATION_TYPE VARCHAR2(255),
  EXTERNAL_REFERENCE_ID VARCHAR2(255),
  TASK_NAME VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_PKEY PRIMARY KEY (ID)
);

CREATE TABLE JBPM_USER_TASKS_ADMIN_GROUPS (
  TASK_ID VARCHAR2(50) NOT NULL,
  GROUP_ID VARCHAR2(255) NOT NULL
  ,CONSTRAINT JBPM_USER_TASKS_ADMIN_GROUPS_PKEY PRIMARY KEY (TASK_ID, GROUP_ID)
);

CREATE TABLE JBPM_USER_TASKS_ADMIN_USERS (
  TASK_ID VARCHAR2(50) NOT NULL,
  USER_ID VARCHAR2(255) NOT NULL
  ,CONSTRAINT JBPM_USER_TASKS_ADMIN_USERS_PKEY PRIMARY KEY (TASK_ID, USER_ID)
);

CREATE TABLE JBPM_USER_TASKS_ATTACHMENTS (
  ID VARCHAR2(50) NOT NULL,
  NAME VARCHAR2(255),
  UPDATED_BY VARCHAR2(255),
  UPDATED_AT TIMESTAMP(6),
  URL VARCHAR2(255),
  TASK_ID VARCHAR2(50) NOT NULL
  ,CONSTRAINT JBPM_USER_TASKS_ATTACHMENTS_PKEY PRIMARY KEY (ID)
);

CREATE TABLE JBPM_USER_TASKS_COMMENTS (
  ID VARCHAR2(50) NOT NULL,
  UPDATED_BY VARCHAR2(255),
  UPDATED_AT TIMESTAMP(6),
  TASK_COMMENT VARCHAR2(1000),
  TASK_ID VARCHAR2(50) NOT NULL
  ,CONSTRAINT JBPM_USER_TASKS_COMMENTS_PKEY PRIMARY KEY (ID)
);

CREATE TABLE JBPM_USER_TASKS_DEADLINE (
  ID NUMBER(10,0) NOT NULL,
  TASK_ID VARCHAR2(50) NOT NULL,
  NOTIFICATION_TYPE VARCHAR2(255) NOT NULL,
  NOTIFICATION_VALUE BLOB,
  JAVA_TYPE VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_DEADLINE_PKEY PRIMARY KEY (ID)
);

CREATE TABLE JBPM_USER_TASKS_DEADLINE_TIMER (
  TASK_ID VARCHAR2(50) NOT NULL,
  NOTIFICATION_JOB_ID VARCHAR2(255) NOT NULL,
  NOTIFICATION_TYPE VARCHAR2(255) NOT NULL,
  NOTIFICATION_VALUE BLOB,
  JAVA_TYPE VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_DEADLINE_TIMER_PKEY PRIMARY KEY (TASK_ID, NOTIFICATION_JOB_ID)
);

CREATE TABLE JBPM_USER_TASKS_EXCLUDED_USERS (
  TASK_ID VARCHAR2(50) NOT NULL,
  USER_ID VARCHAR2(255) NOT NULL
  ,CONSTRAINT JBPM_USER_TASKS_EXCLUDED_USERS_PKEY PRIMARY KEY (TASK_ID, USER_ID)
);

CREATE TABLE JBPM_USER_TASKS_INPUTS (
  TASK_ID VARCHAR2(50) NOT NULL,
  INPUT_NAME VARCHAR2(255) NOT NULL,
  INPUT_VALUE BLOB,
  JAVA_TYPE VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_INPUTS_PKEY PRIMARY KEY (TASK_ID, INPUT_NAME)
);

CREATE TABLE JBPM_USER_TASKS_METADATA (
  TASK_ID VARCHAR2(50) NOT NULL,
  METADATA_NAME VARCHAR2(255) NOT NULL,
  METADATA_VALUE VARCHAR2(512),
  JAVA_TYPE VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_METADATA_PKEY PRIMARY KEY (TASK_ID, METADATA_NAME)
);

CREATE TABLE JBPM_USER_TASKS_OUTPUTS (
  TASK_ID VARCHAR2(50) NOT NULL,
  OUTPUT_NAME VARCHAR2(255) NOT NULL,
  OUTPUT_VALUE BLOB,
  JAVA_TYPE VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_OUTPUTS_PKEY PRIMARY KEY (TASK_ID, OUTPUT_NAME)
);

CREATE TABLE JBPM_USER_TASKS_POTENTIAL_GROUPS (
  TASK_ID VARCHAR2(50) NOT NULL,
  GROUP_ID VARCHAR2(255) NOT NULL
  ,CONSTRAINT JBPM_USER_TASKS_POTENTIAL_GROUPS_PKEY PRIMARY KEY (TASK_ID, GROUP_ID)
);

CREATE TABLE JBPM_USER_TASKS_POTENTIAL_USERS (
  TASK_ID VARCHAR2(50) NOT NULL,
  USER_ID VARCHAR2(255) NOT NULL
  ,CONSTRAINT JBPM_USER_TASKS_POTENTIAL_USERS_PKEY PRIMARY KEY (TASK_ID, USER_ID)
);

CREATE TABLE JBPM_USER_TASKS_REASSIGNMENT (
  ID NUMBER(10,0) NOT NULL,
  TASK_ID VARCHAR2(50) NOT NULL,
  REASSIGNMENT_TYPE VARCHAR2(255) NOT NULL,
  REASSIGNMENT_VALUE BLOB,
  JAVA_TYPE VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_REASSIGNMENT_PKEY PRIMARY KEY (ID)
);

CREATE TABLE JBPM_USER_TASKS_REASSIGNMENT_TIMER (
  TASK_ID VARCHAR2(50) NOT NULL,
  REASSIGNMENT_JOB_ID VARCHAR2(255) NOT NULL,
  REASSIGNMENT_TYPE VARCHAR2(255) NOT NULL,
  REASSIGNMENT_VALUE BLOB,
  JAVA_TYPE VARCHAR2(255)
  ,CONSTRAINT JBPM_USER_TASKS_REASSIGNMENT_TIMER_PKEY PRIMARY KEY (TASK_ID, REASSIGNMENT_JOB_ID)
);

ALTER TABLE JBPM_USER_TASKS_POTENTIAL_USERS ADD CONSTRAINT FK_JBPM_USER_FK_TASKS_POTENTIAL_USERS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_POTENTIAL_GROUPS ADD CONSTRAINT FK_JBPM_USER_TASKS_POTENTIAL_GROUPS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_ADMIN_USERS ADD CONSTRAINT FK_JBPM_USER_TASKS_ADMIN_USERS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_ADMIN_GROUPS ADD CONSTRAINT FK_JBPM_USER_TASKS_ADMIN_GROUPS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_EXCLUDED_USERS ADD CONSTRAINT FK_JBPM_USER_TASKS_EXCLUDED_USERS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_ATTACHMENTS ADD CONSTRAINT FK_USER_TASKS_ATTACHMENTS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_COMMENTS ADD CONSTRAINT FK_USER_TASKS_COMMENTS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_INPUTS ADD CONSTRAINT FK_JBPM_USER_TASKS_INPUTS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_OUTPUTS ADD CONSTRAINT FK_JBPM_USER_TASKS_OUTPUTS_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_METADATA ADD CONSTRAINT FK_JBPM_USER_TASKS_METADATA_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_DEADLINE ADD CONSTRAINT FK_JBPM_USER_TASKS_DEADLINE_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_REASSIGNMENT ADD CONSTRAINT FK_JBPM_USER_TASKS_REASSIGNMENT_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_DEADLINE_TIMER ADD CONSTRAINT FK_JBPM_USER_TASKS_DEADLINE_TIMER_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

ALTER TABLE JBPM_USER_TASKS_REASSIGNMENT_TIMER ADD CONSTRAINT FK_JBPM_USER_TASKS_REASSIGNMENT_TIMER_TID FOREIGN KEY (TASK_ID) REFERENCES JBPM_USER_TASKS (ID) ON DELETE CASCADE;

CREATE SEQUENCE JBPM_USER_TASKS_DEADLINE_SEQ
  INCREMENT BY 50
  START WITH 1
  CACHE 50
;

CREATE SEQUENCE JBPM_USER_TASKS_REASSIGNMENT_SEQ
  INCREMENT BY 50
  START WITH 1
  CACHE 50
;

CREATE INDEX IDX_USERTASKS_TID ON JBPM_USER_TASKS (USER_TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_ADMIN_GROUPS_GID ON JBPM_USER_TASKS_ADMIN_GROUPS (GROUP_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_ADMIN_GROUPS_TID ON JBPM_USER_TASKS_ADMIN_GROUPS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_ADMIN_USERS_TID ON JBPM_USER_TASKS_ADMIN_USERS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_ADMIN_USERS_UID ON JBPM_USER_TASKS_ADMIN_USERS (USER_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_ATTACHMENTS_TID ON JBPM_USER_TASKS_ATTACHMENTS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_COMMENTS_TID ON JBPM_USER_TASKS_COMMENTS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_DEADLINE_TID ON JBPM_USER_TASKS_DEADLINE (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_DEADLINE_TIMER_JID ON JBPM_USER_TASKS_DEADLINE_TIMER (NOTIFICATION_JOB_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_DEADLINE_TIMER_TID ON JBPM_USER_TASKS_DEADLINE_TIMER (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_EXCLUDED_USERS_TID ON JBPM_USER_TASKS_EXCLUDED_USERS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_EXCLUDED_USERS_UID ON JBPM_USER_TASKS_EXCLUDED_USERS (USER_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_INPUTS_TID ON JBPM_USER_TASKS_INPUTS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_METADATA_TID ON JBPM_USER_TASKS_METADATA (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_OUTPUTS_TID ON JBPM_USER_TASKS_OUTPUTS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_POTENTIAL_GROUPS_GID ON JBPM_USER_TASKS_POTENTIAL_GROUPS (GROUP_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_POTENTIAL_GROUPS_TID ON JBPM_USER_TASKS_POTENTIAL_GROUPS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_POTENTIAL_USERS_TID ON JBPM_USER_TASKS_POTENTIAL_USERS (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_POTENTIAL_USERS_UID ON JBPM_USER_TASKS_POTENTIAL_USERS (USER_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_REASSIGNMENT_TID ON JBPM_USER_TASKS_REASSIGNMENT (TASK_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_REASSIGNMENT_TIMER_JID ON JBPM_USER_TASKS_REASSIGNMENT_TIMER (REASSIGNMENT_JOB_ID);

CREATE INDEX IDX_JBPM_USER_TASKS_REASSIGNMENT_TIMER_TID ON JBPM_USER_TASKS_REASSIGNMENT_TIMER (TASK_ID);


